<h3>Change Password for <?php echo $this->zfcUserDisplayName() ?></h3>
<?php if ($status === true) : ?>
<div class="alert alert-success">Password changed successfully.</div>
<?php elseif ($status === false) : ?>
<div class="alert alert-error">Unable to update your password. Please try again.</div>
<?php endif; ?>
<?php

$form = $this->changePasswordForm;

$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/changepassword'));
$form->setAttribute('method', 'post');

$emailElement = $form->get('identity');
$emailElement->setValue($this->zfcUserIdentity()->getEmail());

echo $this->form()->openTag($form);
echo $this->formRow($form->get('identity')) . PHP_EOL;
echo $this->formRow($form->get('credential')) . PHP_EOL;
echo $this->formRow($form->get('newCredential')) . PHP_EOL;
echo $this->formRow($form->get('newCredentialVerify')) . PHP_EOL;
echo $this->formInput($form->get('submit')->setAttribute('class', 'btn btn-default')) . PHP_EOL;
?>


<?php echo $this->form()->closeTag(); ?>
